### ISSUE TITLE
Add support for `seam.events.list`

### ISSUE THREAD

**Issue by seveibar** [seamapi/ruby-legacy#5]

**Comment by jmesserer** [comment]
Any update on this ... ? Using the default sandbox setup.

mbp seam-test % ruby -v
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]

mbp seam-test % gem list seam

*** LOCAL GEMS ***

seamapi (1.8.0)

mbp seam-test % rails c
Loading development environment (Rails 7.0.7.2)
3.0.0 :001 > seam = Seam::Client.new api_key: 'XXXXXXXXXXXXXXXX'
 => #<Seam::Client:0x00007f794da8e3a0 @api_key="XXXXXXXXXXXXXXXX", @base_uri="https://connect.getseam.com", @debug=false>

3.0.0 :002 > seam.events.list
/Users/jdm/.rvm/gems/ruby-3.0.0/gems/seamapi-1.8.0/lib/seam/clients/events.rb:16:in `list': undefined local variable or method `str' for #<Seam::Clients::Events:0x00007f7948e58328 @client=#<Seam::Client:0x00007f794da8e3a0 @api_key="XXXXXXXXXXXXXXXX", @base_uri="https://connect.getseam.com", @debug=false, @events=#<Seam::Clients::Events:0x00007f7948e58328 ...>>> (NameError)
3.0.0 :003 >

**Comment by seveibar** [comment]
huh interesting, I think this is implemented, maybe we have a release issue? CC @abimaelmartell 

https://github.com/seamapi/ruby/blob/main/lib/seam/clients/events.rb#L16

**Comment by seveibar** [comment]
Hi @jmesserer , I validated this is working in seamapi@1.9.0

![image](https://github.com/seamapi/ruby/assets/1910070/ceef9782-4738-4df9-bd25-5a69b0a091b6)
